### ISSUE TITLE
Docker installation - theme does not activate

### ISSUE THREAD

**Issue by m-stefanski** [Kos-M/GogsThemes#14]
I have my Gogs instance deployed in Docker using following environment.yaml file:

```
version: '3'

services:
  gogs:
    image: gogs/gogs
    volumes:
     - /volume1/docker/gogs:/data
    ports:
      - 3000:3000
      - 3022:22
```

I have followed installation instructions (`head.tmpl` creation, copying files), but new theme fails to show after docker restart.

I have tried putting "custom" folder in two locations:

```
/volume1/docker/gogs/custom
/volume1/docker/gogs/gogs/custom
```

And its structure is as follows:

```
./custom/public/* # mv and cp results
./custom/templates/inject/head.tmpl
```

I restart gogs, no new theme is visible.

I feel like I am missing something obvious, or am very bad at reading the instructions. Help please?
